project:
  type: book
  output-dir: _book
  
execute:
  freeze: auto
  
greenpaper:
  version: "v0.4"

book:
  title: "A Green Paper on AI, Data Governance, and Metadata Policies for Europe’s Music Ecosystem"
  subtitle: "Practical Steps Towards a Decentralised and Open European Music Observatory"
  downloads: [pdf, epub, docx] 
  output-file: green-paper-v04
  author:
     - name: "Daniel Antal, CFA"
       orcid: 0000-0001-7513-6760
       affiliations:
               - name: Reprex
                 address: "Saturnusstraat 14"
                 city: The Hague
                 state: Zuid-Holland
                 country: The Netherlands
                 postal-code: "2516 AH"
                 url: https://reprex.nl/
  contributor:
     - name: "Mester, Anna Márta"
       role: "Contributor"
       orcid: 0009-0008-2274-8163
  date: "2024-09-18"
  repo-url: https://github.com/dataobservatory-eu/open-music-data-white-paper
  repo-actions: [edit]
  chapters:
    - index.qmd
    - glossary.qmd
    - context.qmd
    - curation.qmd
    - observatory.qmd
    - ai.qmd
    - conclusion.qmd
    - references.qmd

citation:
  container-title: "Open Music Observatory"
  doi: "10.5281/zenodo.17075796"
  url: https://downloads.reprex.nl/2025/greenpaper/

bibliography: 
    - bib/aibusiness.bib
    - bib/antal.bib
    - bib/BVDA.bib
    - bib/eccch.bib
    - bib/datainteroperability.bib
    - bib/datamodels.bib
    - bib/dataspace.bib
    - bib/decolonisation.bib
    - bib/CISAC.bib
    - bib/collections.bib
    - bib/eulaw.bib
    - bib/eupolicies.bib
    - bib/europeana.bib
    - bib/eXtremeDesign.bib
    - bib/identifiers.bib
    - bib/IFPI.bib
    - bib/ISOData.bib
    - bib/metadata.bib
    - bib/MLC.bib
    - bib/mme.bib
    - bib/musicindustry.bib
    - bib/musicmetadata.bib
    - bib/ontologies.bib
    - bib/opendata.bib
    - bib/OpenMusE.bib
    - bib/services.bib
    - bib/trustworthyAI.bib
    - bib/wikidata.bib
    
csl: csl/chicago-author-date-17th-edition.csl

format:
  html:
    theme: cosmo
  docx: 
    reference-doc: docx/OpenMusE_simple_template.docx
    papersize: a4 
  pdf:
    documentclass: scrreprt
    classoption:
      - paper=a4
      - oneside
      - pagesize
      - BCOR=0mm
      - DIV=13   # try 12–13 for ~25 mm; 14–15 for ~20 mm
    fontsize: 12pt
  epub: default 

editor: visual

